/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export type TasksControllerFindAllSortBy = typeof TasksControllerFindAllSortBy[keyof typeof TasksControllerFindAllSortBy];


export const TasksControllerFindAllSortBy = {
  createdAt: 'createdAt',
  dueDate: 'dueDate',
  title: 'title',
  priority: 'priority',
  status: 'status',
  category: 'category',
} as const;
